name: WordPress WPScan - Vulnerability Discovery Pipeline

on:
  push:
    branches:
      - main

jobs:
  wordpress-wpscan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Docker environment
        run: |
          sudo systemctl start docker
          docker version

      - name: Start MySQL container
        run: |
          docker run -d --name wp-db \
            -e MYSQL_ROOT_PASSWORD=password \
            -e MYSQL_DATABASE=wordpress \
            -e MYSQL_USER=wpuser \
            -e MYSQL_PASSWORD=wppass \
            -p 3306:3306 \
            mysql:5.7

      - name: Start WordPress container
        run: |
          docker run -d --name wp-site \
          --link wp-db:mysql \
          -e WORDPRESS_DB_HOST=host.docker.internal:3306 \
          -e WORDPRESS_DB_USER=wpuser \
          -e WORDPRESS_DB_PASSWORD=wppass \
          -e WORDPRESS_DB_NAME=wordpress \
          -p 8080:80 \
          wordpress:5.0
          
          
          

      - name: Wait for Environment and Inject Plugin
        run: |
          echo "Waiting for database to be ready..."
          until docker exec wp-db mysqladmin ping -h"localhost" -u"wpuser" -p"wppass" --silent; do
            echo "Waiting..."
            sleep 2
          done
          
          echo "Giving WordPress 10 seconds to initialize folders..."
          sleep 10
          
          echo "Creating plugin folder and injecting vulnerable component..."
          docker exec wp-site mkdir -p /var/www/html/wp-content/plugins/contact-form-7
          docker cp ./docker/contact-form-7/. wp-site:/var/www/html/wp-content/plugins/contact-form-7

          docker cp ./docker/contact-form-7 wp-site:/var/www/html/wp-content/plugins/

      - name: Install Ruby and WPScan
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential libcurl4-openssl-dev zlib1g-dev
          sudo gem install wpscan

      - name: Run WPScan
        run: |
          wpscan --url http://localhost:8080 --enumerate u,vp,vt --force || true
